export const UPDATE_INGREDIENT = 'UPGRADE_INGREDIENT';
export const TOGGLE_PURCHASABLE = 'TOGGLE_PURCHASABLE';

export const STORE_ORDERS = 'STORE_ORDERS';
export const ORDER_START='ORDER_START';
export const ORDER_SUCCESS='ORDER_SUCCESS';
export const ORDER_FAIL='ORDER_FAIL';

// auth
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';