export const UPDATE_INGREDIENT = 'UPGRADE_INGREDIENT';
// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const TOGGLE_PURCHASABLE = 'TOGGLE_PURCHASABLE';
